version: '2'

services:
  postgresserver:
     image: lizapostgres
     restart: always
     build:
       context: ./DB
       dockerfile: Dockerfile
     environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: Qwerty123
         POSTGRES_DB: Interview_questions
     volumes:
       - pgdata:/var/lib/postgresql/data
     networks:
       - mynetwork

  aspnetcorepostgresqldocker:
     image: aspnetcorepostgresqldocker
     ports:
       - 5001:80
     build:
       context: ./PL
       dockerfile: Dockerfile
     links:
       - postgresserver
     depends_on:
       - "postgresserver"
     networks:
       - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
     driver: bridge