version: '2'

services:
  lizapostgres:
     image: lizapostgres
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 5432:5432
     environment:
         POSTGRES_PASSWORD: Qwerty123
     volumes:
       - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: